apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: olehalv

resources:
  - deployment.yaml
  - service.yaml
  - http-route.yaml

configMapGenerator:
  - name: code-config
    namespace: olehalv
    literals:
      - PGUID=1000
      - PGID=1000
      - TZ=Etc/UTC
