apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: olehalv

resources:
  - deployment.yaml
  - service.yaml
  - http-route.yaml

configMapGenerator:
  - name: doom-config
    namespace: olehalv
    literals:
      - VNC_PW=password
